src/InstaNet.Web/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InstaNet.Web.ViewModels
{
    public class LoginViewModel
    {
        [DataType(DataType.EmailAddress)]
        [Required]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }
    }
}

src/InstaNet.Web/ViewModels/ProfileViewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace InstaNet.Web.ViewModels
{
    public class ProfileViewModel
    {
        public IFormFile Image { get; set; }

        [Required]
        public string DisplayName { get; set; }

        public string Bio { get; set; }
    }
}

src/InstaNet.Web/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InstaNet.Web.ViewModels
{
    public class RegisterViewModel
    {
        [DataType(DataType.EmailAddress)]
        [Required]
        public string Email { get; set; }

        [Required]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Required]
        public string ConfirmPassword { get; set; }
    }
}

src/InstaNet.Web/Pages/About.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages
{
    [Authorize]
    public class AboutModel : PageModel
    {
        private readonly RepositoryContext repositoryContext;
        private readonly UserManager<ApplicationUser> userManager;

        public AboutModel(RepositoryContext repositoryContext, UserManager<ApplicationUser> userManager)
        {
            this.repositoryContext = repositoryContext;
            this.userManager = userManager;
        }

        [BindProperty]
        public IReadOnlyList<Post> Timeline { get; set; }

        [BindProperty]
        public Replay Replay { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);
            var following = currentUser.Profile.Following.Select(x => x.FollowerId);

            this.Timeline = this.repositoryContext.Posts
                .Where(x => following.Contains(x.ProfileId) || x.ProfileId == currentUser.ProfileId)
                .Take(20).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostReplay(string id)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

                this.Replay.Id = Guid.NewGuid();
                this.Replay.Profile = currentUser.Profile;
                this.Replay.Post = this.repositoryContext.Posts.FirstOrDefault(x => x.Id.ToString() == id);

                await this.repositoryContext.Replays.AddAsync(Replay);
                await this.repositoryContext.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnGetLike(string id)
        {
            var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

            var result = this.repositoryContext.Likes
                .FirstOrDefault(x => x.ProfileId == currentUser.ProfileId && x.PostId == Guid.Parse(id));

            if (result == null)
            {
                await this.repositoryContext.Likes.AddAsync(new Like
                {
                    Id = Guid.NewGuid(),
                    PostId = Guid.Parse(id),
                    ProfileId = currentUser.Profile.Id
                });
            }
            else
            {
                this.repositoryContext.Likes.Remove(result);
            }

            await this.repositoryContext.SaveChangesAsync();

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnGetLogOut()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToPage("/Index");
        }
    }
}

src/InstaNet.Web/Pages/Account/Login.cshtml.cs
using InstaNet.DataAccess.Identity;
using InstaNet.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages.Account
{
    [ValidateAntiForgeryToken]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;

        public LoginModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        [BindProperty]
        public LoginViewModel LoginViewModel { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (LoginViewModel.Email.IndexOf("@") > -1)
            {
                var user = await this.userManager.FindByEmailAsync(LoginViewModel.Email);

                if (user != null)
                {
                    var result = await this.signInManager.PasswordSignInAsync(user, LoginViewModel.Password, true, true);

                    if (result.Succeeded)
                    {
                        return RedirectToPage("/Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Something dosen´t work");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "User not exists");
                }
            }

            return Page();
        }
    }
}

src/InstaNet.Web/Pages/Account/Profile.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages.Account
{
    [Authorize]
    public class ProfileModel : PageModel
    {
        private readonly RepositoryContext repositoryContext;
        private readonly UserManager<ApplicationUser> userManager;

        public ProfileModel(RepositoryContext repositoryContext, UserManager<ApplicationUser> userManager)
        {
            this.repositoryContext = repositoryContext;
            this.userManager = userManager;
        }

        [BindProperty]
        public Profile Profile { get; set; }

        public async Task<IActionResult> OnGet(string id)
        {
            this.Profile = await this.repositoryContext.Profiles.FindAsync(Guid.Parse(id));
            return Page();
        }

        public async Task<IActionResult> OnGetFollow(string id)
        {
            var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

            var result = currentUser.Profile.Following
                .FirstOrDefault(x => x.FollowingId == currentUser.ProfileId && x.FollowerId == Guid.Parse(id));

            if (result == null)
            {
                await this.repositoryContext.Follows.AddAsync(new Follow
                {
                    Id = Guid.NewGuid(),
                    FollowerId = Guid.Parse(id),
                    FollowingId = currentUser.ProfileId,
                });
            }
            else
            {
                this.repositoryContext.Follows.Remove(result);
            }

            await this.repositoryContext.SaveChangesAsync();

            return RedirectToPage("/Account/Profile", new { Id = id });
        }
    }
}

src/InstaNet.Web/Pages/Account/Register.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using InstaNet.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages.Account
{
    [ValidateAntiForgeryToken]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RepositoryContext repositoryContext;

        public RegisterModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, RepositoryContext repositoryContext)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.repositoryContext = repositoryContext;
        }

        [BindProperty]
        public RegisterViewModel RegisterViewModel { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if ((RegisterViewModel.Email.IndexOf("@") > -1) && (RegisterViewModel.Password.Equals(RegisterViewModel.ConfirmPassword)))
            {
                var user = await this.userManager.FindByEmailAsync(RegisterViewModel.Email);

                if (user == null)
                {
                    Profile profile = new Profile
                    {
                        UserName = RegisterViewModel.UserName,
                        DisplayName = RegisterViewModel.UserName,
                        Bio = RegisterViewModel.UserName + "´s Bio",
                        Image = await System.IO.File.ReadAllBytesAsync(".//wwwroot//Images//User.PNG"),
                        Created = DateTime.Now,
                        Modified = DateTime.Now
                    };

                    await repositoryContext.Profiles.AddAsync(profile);
                    await repositoryContext.SaveChangesAsync();

                    ApplicationUser applicationUser = new ApplicationUser
                    {
                        Email = RegisterViewModel.Email,
                        UserName = RegisterViewModel.UserName,
                        Profile = profile
                    };

                    var result = await this.userManager.CreateAsync(applicationUser, RegisterViewModel.Password);

                    if (result.Succeeded)
                    {
                        await this.signInManager.PasswordSignInAsync(applicationUser, RegisterViewModel.Password, true, true);
                        return RedirectToPage("/Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Something dosen´t work");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "User already exists");
                }
            }
            else
            {
                ModelState.AddModelError("", "Passwords don´t match");
            }

            return Page();
        }
    }
}

src/InstaNet.Web/Pages/Account/Settings.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using InstaNet.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.IO;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages.Account
{
    [Authorize, ValidateAntiForgeryToken]
    public class SettingsModel : PageModel
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RepositoryContext repositoryContext;

        public SettingsModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, RepositoryContext repositoryContext)
        {
            this.userManager = userManager;
            this.repositoryContext = repositoryContext;
        }

        [BindProperty]
        public Profile Profile { get; set; }

        [BindProperty]
        public ProfileViewModel ProfilViewModel { get; set; }

        public async Task<IActionResult> OnGet(string id)
        {
            this.Profile = await this.repositoryContext.Profiles.FindAsync(Guid.Parse(id));
            var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

            if (currentUser.ProfileId != this.Profile.Id)
            {
                return RedirectToPage("/Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostSave(string id)
        {
            if (ModelState.IsValid)
            {
                var editProfil = await this.repositoryContext.Profiles.FindAsync(Guid.Parse(id));

                editProfil.DisplayName = this.ProfilViewModel.DisplayName;
                editProfil.Bio = this.ProfilViewModel.Bio;
                editProfil.Modified = DateTime.Now;

                if (this.ProfilViewModel.Image != null)
                {
                    editProfil.Image = FileToByteArray(this.ProfilViewModel.Image);
                }

                this.repositoryContext.Profiles.Update(editProfil);

                await this.repositoryContext.SaveChangesAsync();

                return RedirectToPage("/Account/Profile", new { Id = id });
            }
            return RedirectToPage("/Account/Settings", new { Id = id });
        }

        private byte[] FileToByteArray(IFormFile _formFile)
        {
            using (MemoryStream _memoryStream = new MemoryStream())
            {
                _formFile.CopyTo(_memoryStream);
                return _memoryStream.ToArray();
            }
        }
    }
}

src/InstaNet.Web/Pages/Account/Login.cshtml
@page
@model InstaNet.Web.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login";
}

<div class="column-container content-container" style="width: 100%; margin: auto; max-width: 350px">
    <form method="post">
        <h1 style="text-align: center; color: #3A1156;font-size: 30px; margin-bottom: 50px">Instagram-Ecole hexagone</h1>
        <div class="form-group">
            <label asp-for="LoginViewModel.Email"></label>
            <input asp-for="LoginViewModel.Email" placeholder="Email" />
        </div>

        <div class="form-group">
            <label asp-for="LoginViewModel.Password"></label>
            <input asp-for="LoginViewModel.Password" placeholder="Password" />
        </div>

        
    <head>
            <style>
                input[type=submit] {
                    background-color: #F9CD03;
                    border: none;
                    color: #3A1156;
                    padding: 16px 32px;
                    text-decoration: none;
                    margin: 4px 2px;
                    cursor: pointer;
                    font-size: 16px;
                    font-weight: bold;
                }
            </style>
     </head>

    <input class="click-link" type="submit" value="Login" />

        <div class="errors" asp-validation-summary="All"></div>
    </form>

    <hr />

    <a  asp-page="/Account/Register" class="click-link" style="text-align: center; padding: 10px">créer un nouveau compte </a>
</div>

src/InstaNet.Web/Pages/Account/Profile.cshtml
@page "{id}"
@model InstaNet.Web.Pages.Account.ProfileModel

@{
    ViewData["Title"] = "Profile";
}

<div class="column-container" style="max-width: 935px;">
    <div class="profil-container">
        <a asp-page="/Account/Profile" asp-route-id="@Model.Profile.Id"><img class="profil-img" src="data:image;base64,@System.Convert.ToBase64String(Model.Profile.Image)" height="100" width="100" /></a>

        <div class="column-container">
            <div class="row-container">
                <a style="font-size: 30px; font-weight: 100" asp-page="/Account/Profile" asp-route-id="@Model.Profile.Id">@Model.Profile.UserName</a>

                @if (User.Identity.GetProfileId() == Model.Profile.Id)
                {
            <a style="margin-left: 15px;" class="button-link" asp-page="/Account/Settings" asp-route-id="@Model.Profile.Id">Settings</a> }
                        else
                        {
            <a style="margin-left: 15px;" class="button-link" asp-page-handler="Follow" asp-route-id="@Model.Profile.Id">Follow</a>
                            <a style="margin-left: 15px; margin-top: 3px" class="button-link" asp-page="/Index" asp-page-handler="LogOut">LogOut</a>
                                            <a style="margin-left: 15px; margin-top: 3px" class="button-link" asp-page="/About" asp-page-handler="About">About</a>}
            </div>

            <p style="margin-top: 15px;"><strong>@Model.Profile.DisplayName</strong></p>

            <div class="row-container" style="margin-top: 20px;">
                <p style="margin-right: 15px; font-size: 15px"><strong style="font-size: 15px">@Model.Profile.Posts.Count</strong> posts</p>
                <p style="margin-right: 15px; font-size: 15px"><strong style="font-size: 15px">@Model.Profile.Followers.Count</strong> followers</p>
                <p style="font-size: 15px"><strong style="font-size: 15px">@Model.Profile.Following.Count</strong> following</p>
            </div>

            <p style="margin-top: 20px;">@Model.Profile.Bio</p>
        </div>
    </div>

    <hr style="margin-top: 50px; margin-bottom: 25px;" />


    <div class="img-container">
        @foreach (var post in Model.Profile.Posts)
        {
            <div class="post-img">
                <a asp-page="/Content/Details" asp-route-id="@post.Id"><img src="data:image;base64,@System.Convert.ToBase64String(post.Pictures.First().File)" /></a>
            </div>
        }
    </div>
</div>

src/InstaNet.Web/Pages/Account/Register.cshtml
@page
@model InstaNet.Web.Pages.Account.RegisterModel
@{
    ViewData["Title"] = "Register";
}

<div class="content-container column-container" style="width: 100%; margin: auto; max-width: 350px">
    <form method="post">
        <h1 style="text-align: center; font-size: 25px; margin-bottom: 50px">Instagram-Ecole hexagone</h1>
        <div class="form-group">
            <label asp-for="RegisterViewModel.Email"></label>
            <input asp-for="RegisterViewModel.Email" placeholder="Email" />
        </div>

        <div class="form-group">
            <label asp-for="RegisterViewModel.UserName"></label>
            <input asp-for="RegisterViewModel.UserName" placeholder="Password" />
        </div>

        <div class="form-group">
            <label asp-for="RegisterViewModel.Password"></label>
            <input asp-for="RegisterViewModel.Password" placeholder="Password" />
        </div>

        <div class="form-group">
            <label asp-for="RegisterViewModel.ConfirmPassword"></label>
            <input asp-for="RegisterViewModel.ConfirmPassword" placeholder="Password" />
        </div>

        <head>
            <style>
                input[type=submit] {
                    background-color: #F9CD03;
                    border: none;
                    color: #3A1156;
                    padding: 16px 32px;
                    text-decoration: none;
                    margin: 4px 2px;
                    cursor: pointer;
                    font-size: 16px;
                    font-weight: bold;
                }
            </style>
        </head>
        <input class="click-link" type="submit" value="Register" />

        <div class="errors" asp-validation-summary="All"></div>
    </form>

    <hr />

    <a asp-page="/Account/Login" class="click-link" style="text-align: center; padding: 10px">Se connecter </a>
</div>

src/InstaNet.Web/Pages/Account/Settings.cshtml
@page "{id}"
@model InstaNet.Web.Pages.Account.SettingsModel
@{
    ViewData["Title"] = "Settings";
}

<div class="content-container" style="width: 100%; margin: auto; max-width: 350px">
    <form method="post" enctype="multipart/form-data" asp-route-id="@Model.Profile.Id" asp-page-handler="Save">
        <div class="form-group">
            <label asp-for="ProfilViewModel.Image"></label>
            <label for="imageInput">
                <img class="main-img" id="imageDisplay" src="data:image;base64,@System.Convert.ToBase64String(Model.Profile.Image)" alt="COVER" height="50" width="50" style="object-fit: scale-down; margin: 0px; border-radius: 50px;" />
                <input asp-for="ProfilViewModel.Image" id="imageInput" />
            </label>
        </div>

        <div class="form-group">
            <label asp-for="ProfilViewModel.DisplayName"></label>
            <input asp-for="ProfilViewModel.DisplayName" value="@Model.Profile.DisplayName" />
        </div>

        <div class="form-group">
            <label asp-for="ProfilViewModel.Bio"></label>
            <input asp-for="ProfilViewModel.Bio" value="@Model.Profile.Bio" />
        </div>

        <div class="form-group">
            <input type="submit" value="Save" />
        </div>

        <div class="errors" asp-validation-summary="All"></div>
    </form>
</div>