src/InstaNet.Web/Pages/About.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages
{
    [Authorize]
    public class AboutModel : PageModel
    {
        private readonly RepositoryContext repositoryContext;
        private readonly UserManager<ApplicationUser> userManager;

        public AboutModel(RepositoryContext repositoryContext, UserManager<ApplicationUser> userManager)
        {
            this.repositoryContext = repositoryContext;
            this.userManager = userManager;
        }

        [BindProperty]
        public IReadOnlyList<Post> Timeline { get; set; }

        [BindProperty]
        public Replay Replay { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);
            var following = currentUser.Profile.Following.Select(x => x.FollowerId);

            this.Timeline = this.repositoryContext.Posts
                .Where(x => following.Contains(x.ProfileId) || x.ProfileId == currentUser.ProfileId)
                .Take(20).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostReplay(string id)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

                this.Replay.Id = Guid.NewGuid();
                this.Replay.Profile = currentUser.Profile;
                this.Replay.Post = this.repositoryContext.Posts.FirstOrDefault(x => x.Id.ToString() == id);

                await this.repositoryContext.Replays.AddAsync(Replay);
                await this.repositoryContext.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnGetLike(string id)
        {
            var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

            var result = this.repositoryContext.Likes
                .FirstOrDefault(x => x.ProfileId == currentUser.ProfileId && x.PostId == Guid.Parse(id));

            if (result == null)
            {
                await this.repositoryContext.Likes.AddAsync(new Like
                {
                    Id = Guid.NewGuid(),
                    PostId = Guid.Parse(id),
                    ProfileId = currentUser.Profile.Id
                });
            }
            else
            {
                this.repositoryContext.Likes.Remove(result);
            }

            await this.repositoryContext.SaveChangesAsync();

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnGetLogOut()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToPage("/Index");
        }
    }
}

src/InstaNet.Web/Pages/Content/Details.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages.Content
{
    public class DetailsModel : PageModel
    {
        private readonly RepositoryContext repositoryContext;
        private readonly UserManager<ApplicationUser> userManager;

        public DetailsModel(RepositoryContext repositoryContext, UserManager<ApplicationUser> userManager)
        {
            this.repositoryContext = repositoryContext;
            this.userManager = userManager;
        }

        [BindProperty]
        public Post Post { get; set; }

        [BindProperty]
        public Replay Replay { get; set; }

        public async Task<IActionResult> OnGet(string id)
        {
            this.Post = await this.repositoryContext.Posts.FindAsync(Guid.Parse(id));
            return Page();
        }

        public async Task<IActionResult> OnPostReplay(string id)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await this.userManager.FindByNameAsync(User.Identity.Name);

                this.Replay.Id = Guid.NewGuid();
                this.Replay.Profile = currentUser.Profile;
                this.Replay.Post = this.repositoryContext.Posts.FirstOrDefault(x => x.Id.ToString() == id);
                this.Replay.Created = DateTime.Now;
                this.Replay.Modified = DateTime.Now;

                await this.repositoryContext.Replays.AddAsync(Replay);
                await this.repositoryContext.SaveChangesAsync();
            }

            return RedirectToPage("Details", new { Id = id });
        }
    }
}

src/InstaNet.Web/Pages/Content/New.cshtml.cs
using InstaNet.ApplicationCore.Entities;
using InstaNet.DataAccess.Data;
using InstaNet.DataAccess.Identity;
using InstaNet.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.IO;
using System.Threading.Tasks;

namespace InstaNet.Web.Pages.Content
{
    [Authorize, ValidateAntiForgeryToken]
    public class NewModel : PageModel
    {
        private readonly RepositoryContext repositoryContext;
        private readonly UserManager<ApplicationUser> userManager;

        public NewModel(RepositoryContext repositoryContext, UserManager<ApplicationUser> userManager)
        {
            this.repositoryContext = repositoryContext;
            this.userManager = userManager;
        }

        [BindProperty]
        public PostViewModel PostViewModel { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostNew(string id)
        {
            if (ModelState.IsValid)
            {
                var post = new Post
                {
                    Id = Guid.NewGuid(),
                    Caption = PostViewModel.Caption,
                    ProfileId = Guid.Parse(id),
                    Created = DateTime.Now,
                    Modified = DateTime.Now
                };

                await this.repositoryContext.Posts.AddAsync(post);

                var picture = await this.repositoryContext.Pictures.AddAsync(new Picture
                {
                    Id = Guid.NewGuid(),
                    File = FileToByteArray(PostViewModel.Picture),
                    PostId = post.Id,
                    Created = DateTime.Now,
                    Modified = DateTime.Now
                });

                await this.repositoryContext.SaveChangesAsync();

                return RedirectToPage("/Content/Details", new { Id = post.Id });
            }

            return Page();
        }

        private byte[] FileToByteArray(IFormFile _formFile)
        {
            using (MemoryStream _memoryStream = new MemoryStream())
            {
                _formFile.CopyTo(_memoryStream);
                return _memoryStream.ToArray();
            }
        }
    }
}

src/InstaNet.Web/Pages/Content/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InstaNet.Web.Pages.Content
{
    public class SearchModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/InstaNet.Web/Pages/Content/Details.cshtml
@page "{id}"
@model InstaNet.Web.Pages.Content.DetailsModel
@{
    ViewData["Title"] = "Details";
}

<div class="post-container" style="margin: auto;">
    <div class="row-container" style="">
        <div class="column-container">
            <img class="main-img" src="data:image;base64,@System.Convert.ToBase64String(Model.Post.Pictures.First().File)" style="margin: auto; max-width: 600px; max-height: 600px" />
        </div>

        <div style="min-width: 335px; border: 1px solid rgba(0,0,0,.0975)">

            <div class="row-container" style="padding: 7px; border-bottom: 1px solid rgba(0,0,0,.0975)">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.Post.Profile.Image)" height="35" width="35" style="border-radius: 50px; margin: 3px; margin-left: 10px" />
                <a asp-page="/Account/Profile" asp-route-id="@Model.Post.Profile.Id">@Model.Post.Profile.UserName</a>
            </div>

            <div>
                <div class="column-container" style="max-height: 320px; overflow: auto;">

                    <div class="column-container" style="margin-top: 10px;">
                        <div class="row-container">
                            <img src="data:image;base64,@System.Convert.ToBase64String(Model.Post.Profile.Image)" height="30" width="30" style="border-radius: 50px; margin-left: 18px" />
                            <a style="margin-top: 7px;" asp-page="/Account/Profile" asp-route-id="@Model.Post.Profile.Id">@Model.Post.Profile.UserName</a>
                            <p style="margin-top: 7px;">@Model.Post.Caption</p>
                        </div>
                    </div>

                    @foreach (var replay in Model.Post.Replays.OrderBy(x => x.Created))
                    {
                        <div class="column-container" style="margin-top: 10px;">
                            <div class="row-container">
                                <img src="data:image;base64,@System.Convert.ToBase64String(replay.Profile.Image)" height="30" width="30" style="border-radius: 50px; margin-left: 18px" />
                                <a style="margin-top: 7px;" asp-page="/Account/Profile" asp-route-id="@replay.Profile.Id">@replay.Profile.UserName</a>
                                <p style="margin-top: 7px;">@replay.Text</p>
                            </div>
                            <p style="color: lightgray; margin-left: 65px; margin-top: 5px; font-size: 12px">@replay.TimeAgo()</p>
                        </div>
                    }
                </div>

                <div class="row-container" style="margin-top: 10px;">
                    <hr />
                    <a><strong>@Model.Post.Likes.Count Likes</strong></a>
                    <a style="margin-top: 8px" class="click-link" asp-page="/Index" asp-page-handler="Like" asp-route-id="@Model.Post.Id">Like</a>
                </div>

                <div class="column-container" style="padding-bottom: 2.5px; margin-top: 3px; bottom: 2px">
                    <hr />
                    <form class="row-container" method="post" asp-page-handler="Replay" asp-route-id="@Model.Post.Id">
                        <input asp-for="Replay.Text" placeholder="Add a comment..." style="margin-top: 3px; border: none; width: 80%; text-align: left; padding: 15px;" />
                        <button class="click-link" style="margin-right: 28px;">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/InstaNet.Web/Pages/Content/New.cshtml
@page
@model InstaNet.Web.Pages.Content.NewModel

@{
    ViewData["Title"] = "New";
}

<div class="post-container">
    <div class="column-container">
        <div class="row-container" style="padding: 7px; border: 1px solid rgba(0,0,0,.0975)">
            <a style="margin-top: 0px" asp-page="/Account/Profile" asp-route-id="@User.Identity.GetProfileId()"><img src="data:image;base64,@User.Identity.GetProfileImage()" height="35" width="35" style="border-radius: 50px; margin: 3px; margin-left: 10px" /></a>
            <a asp-page="/Account/Profile" asp-route-id="@User.Identity.GetProfileId()">@User.Identity.GetProfileName()</a>
        </div>

        <form method="post" asp-route-id="@User.Identity.GetProfileId()" asp-page-handler="New" enctype="multipart/form-data" style="margin: 0px;">
            <div class="column-container" style="margin: 0px;">
                <label for="imageInput" style="margin: 0px;">
                    <img class="main-img" id="imageDisplay" src="~/images/Select.png" alt="COVER" style="margin: 0px;" />
                    <input asp-for="PostViewModel.Picture" id="imageInput" />
                </label>
            </div>

            <div style="border: 1px solid rgba(0,0,0,.0975); margin: 0px; padding: 15px">
                <div class="row-container">
                    <p style="margin-top: 11px; margin-right: 5px;">Caption</p>
                    <input asp-for="PostViewModel.Caption" style="width: 100%;" />
                </div>

                <div class="form-group">
                    <input type="submit" value="Post" />
                </div>

                <div class="errors" asp-validation-summary="All"></div>
            </div>
        </form>
    </div>
</div>

src/InstaNet.Web/Pages/Content/Search.cshtml
@page
@model InstaNet.Web.Pages.Content.SearchModel
@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>